Homework1
made-ml-in-prod-2021/malyginvlad pull request #2
Opened 2021-05-05 18:25 UTC by malyginvlad

В jupyter notebooks есть небольшой файл с EDA для первичного ознакомления с данными.
Полный pipeline модели с чтением, трансформацией данных, обучением и предсказанием находится в файле train_pipeline.py. Сначала данные считываются, разбиваются на train и test, затем происходит заполнение пропущенных данных и применение стандартизации к данным. Обучение происходит с использованием модели RandomForestClassifier. Для оценки модели использовались метрики: precision, recall и f1.
После обучения модели на тренировочных данных, она сохраняется в файле model.pkl, а полученные метрики сохраняются в файл metrics.json. Аналогично для обучения на сгенерированных данных.

2021-05-06 19:32 UTC, KernelA commented on .idea/inspectionProfiles/Project_Default.xml
> +<component name="InspectionProjectProfileManager">
Это и далее `.idea` по идее служебные файлы. Не совсем понятно зачем их добавлять в репозиторий.

2021-05-06 19:52 UTC, KernelA approved these changes
Окружение настраивается.

Тесты запускаются.

Обучение работает. Модель сохраняется. Комментарии написал свои.

2021-05-06 19:52 UTC, KernelA commented on ml_project/data/make_dataset.py
> +def read_data(path: str = "ml_project/data/raw/heart.csv") -> pd.DataFrame:
Я бы тут не оставлял такой параметр по умолчанию как целый путь к файлу.

2021-05-06 19:52 UTC, KernelA commented on ml_project/features/build_features.py
> +from ml_project.entities.feature_params import FeatureParams
Раз `build_features.py` находятся внутри пакета, то лучше относительные импорты использовать.

Так в некоторых случаях можно столкнутся с ошибками.

2021-05-06 19:52 UTC, KernelA commented on ml_project/models/model_train.py
> +        pickle.dump(model, file)
Тут бы зафиксировал версию протокола для PICKLE. Т. к. по умолчанию может меняться в зависимости от версии Python и потом файл не откроется.

2021-05-06 19:52 UTC, KernelA commented on ml_project/tests/data/test_make_dataset.py
> +    assert df_test.isna().sum().sum() >= 0, "Test data does not have NaNs"
Тут можно на `any()` заменить

2021-05-06 19:52 UTC, KernelA commented on ml_project/tests/features/test_process_features.py
> +        assert features.isna().sum().sum() == 0, \
Тут аналогично про `any`

2021-05-06 19:52 UTC, KernelA commented on ml_project/tests/models/test_metrics.py
> +    assert os.path.exists(params.output_model_path), f"No such file {params.output_model_path}"
Тут тогда лучше проверять на `isfile`

2021-05-06 19:52 UTC, KernelA commented on ml_project/tests/models/test_train_model.py
> +from py._path.local import LocalPath
Лучше тогда pathlib использовать. В документации к этой библиотеки указано:

> Note: The ‘py’ library is in “maintenance mode” and so is not recommended for new projects. Please check out pathlib or pathlib2 for path operations.

2021-05-06 19:52 UTC, KernelA commented on setup.py
> +    author="Vladislav Malygin",
Тут ещё версии Python не хватает минимально необходимой

2021-05-07 07:00 UTC, malyginvlad commented on .idea/inspectionProfiles/Project_Default.xml
> +<component name="InspectionProjectProfileManager">
Согласен, не заметил их, думал что в гитигнор они прописаны)

2021-05-07 07:01 UTC, malyginvlad commented on ml_project/data/make_dataset.py
> +def read_data(path: str = "ml_project/data/raw/heart.csv") -> pd.DataFrame:
хорошо, убрал

2021-05-07 07:01 UTC, malyginvlad commented on ml_project/features/build_features.py
> +from ml_project.entities.feature_params import FeatureParams
спасибо, не заметил, согласен, что бывают ошибки при изменении кода в больших проектах))

2021-05-07 07:02 UTC, malyginvlad commented on ml_project/models/model_train.py
> +        pickle.dump(model, file)
добавил версию протокола 0, для совместимости

2021-05-07 07:02 UTC, malyginvlad commented on ml_project/tests/data/test_make_dataset.py
> +    assert df_test.isna().sum().sum() >= 0, "Test data does not have NaNs"
тут скорее всего я не правильно обозначил, что хотел протестировать, я хотел посчитать количество нуллов в данных, немного исправил и теперь вывожу количество, если оно не равно 0

2021-05-07 07:03 UTC, malyginvlad commented on ml_project/tests/features/test_process_features.py
> +        assert features.isna().sum().sum() == 0, \
тут скорее всего я не правильно обозначил, что хотел протестировать, я хотел посчитать количество нуллов в данных, немного исправил и теперь вывожу количество, если оно не равно 0

2021-05-07 07:03 UTC, malyginvlad commented on ml_project/tests/models/test_metrics.py
> +    assert os.path.exists(params.output_model_path), f"No such file {params.output_model_path}"
вы правы, exists иногда может выдавать неправильное значение, мы ведь всё же файл ищем)) Исправил

2021-05-07 07:04 UTC, malyginvlad commented on ml_project/tests/models/test_train_model.py
> +from py._path.local import LocalPath
хорошо, поменял на pathlib

2021-05-07 07:04 UTC, malyginvlad commented on setup.py
> +    author="Vladislav Malygin",
добавил версию питона >= 3.4, чтобы избежать ошибок в более ранних версиях

2021-05-07 11:35 UTC, Mikhail-M requested changes

2021-05-07 11:35 UTC, Mikhail-M commented on README.md
> +Данный проект оцениваю на 36 баллов.
А почему так?

ci, hydra, custorm transormers не вижу -- это уже максимум 29

2021-05-07 12:20 UTC, malyginvlad commented on README.md
> +Данный проект оцениваю на 36 баллов.
Я не правильно считаю баллы (плохой из меня математик), переделал табличку и насчитал заново 28 баллов))

2021-05-09 13:10 UTC, KernelA approved these changes

2021-05-25 03:04 UTC, andreitsy commented on setup.py
> +    python_requires='>=3.4'
пропущена запятая
```
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-zjyc7m8j/setup.py", line 6
        packages=find_packages(),
        ^
    SyntaxError: invalid syntax
```

2021-05-25 03:29 UTC, andreitsy approved these changes
Итого:

0) 2б 
1) 2б 
2) 2б
3) 2б
4) 3б
5) 3б
6) 3б
7) 3б
8) 3б
9) 3б
10) Не написано как сделать предикт на основе модели, 1б
11) Не вижу использования hydra. Или я что-то пропустил? 0 баллов за этот пункт.
12) Не вижу использования CI, тоже 0
13) 1б

Сниму один балл за нерабочий код в setup.py, а в целом всё супер:)

Оцениваю **в 27 баллов.**

2021-05-25 07:47 UTC, malyginvlad commented on setup.py
> +    python_requires='>=3.4'
эх, баг после исправления, спасибо))

2021-05-25 07:47 UTC, merged